### ISSUE TITLE
Can't register in 0.1.2

### ISSUE THREAD

**Issue by nolim1t** [getumbrel/umbrel-manager#20]
When trying to register this is what happens in the logs

```
umbrel-manager
Cannot read property 'data' of undefined
/v1/account/register
TypeError: Cannot read property 'data' of undefined
    at Object.register (/usr/src/app/logic/auth.js:223:44)
    at async /usr/src/app/routes/v1/account.js:89:17
    at async /usr/src/app/utils/safeHandler.js:8:14

```

**Comment by nolim1t** [comment]
I'll investigate this more.. maybe some weird local thing
